import React, { useCallback, useEffect, useState } from "react";
import { Card, Col, Row, Statistic, Table, Tag, Button, Spin, Alert, Modal, App, Empty } from "antd";
import {
  FileTextOutlined,
  CalendarOutlined,
  NumberOutlined,
  ReloadOutlined,
  DollarCircleOutlined,
  DownloadOutlined,
  EyeOutlined,
  SaveOutlined
} from "@ant-design/icons";
import { getDashboardData } from "../api";
import { getSavedPIs, downloadStoredPI } from "../piStorage";
import { formatINR } from "../formatCurrency";
import { PILogEntry, DashboardStats, User, StoredPI } from "../types";
import { PIPreview } from "./PIPreview";

interface DashboardProps {
  currentUser: User;
  onNavigateToCreate: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onNavigateToCreate }) => {
  const { message } = App.useApp();
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [recentPIs, setRecentPIs] = useState<PILogEntry[]>([]);
  const [savedPIs, setSavedPIs] = useState<StoredPI[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [previewPI, setPreviewPI] = useState<StoredPI | null>(null);

  const loadSavedPIs = useCallback(async () => {
    const stored = await getSavedPIs();
    setSavedPIs(stored);
  }, []);

  const fetchDashboard = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await getDashboardData();
      setStats(result.stats);
      setRecentPIs(result.recentPIs);
      await loadSavedPIs();
    } catch (err: any) {
      setError(err.message || "Failed to load dashboard data");
      await loadSavedPIs();
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboard();
  }, []);

  const handleDownloadSaved = async (piNumber: string) => {
    const ok = await downloadStoredPI(piNumber);
    if (ok) {
      message.success("PDF downloaded successfully!");
    } else {
      message.error("Saved PDF not found. Generate this PI again to store a copy.");
    }
  };

  const columns = [
    {
      title: "PI Number",
      dataIndex: "piNumber",
      key: "piNumber",
      render: (text: string) => <Tag color="blue" style={{ fontSize: "0.9rem", padding: "4px 8px" }}>{text}</Tag>,
    },
    {
      title: "Date",
      dataIndex: "date",
      key: "date",
      render: (dateStr: string) => new Date(dateStr).toLocaleDateString("en-IN", {
        year: "numeric",
        month: "short",
        day: "numeric"
      })
    },
    {
      title: "Customer Name",
      dataIndex: "customerName",
      key: "customerName",
      ellipsis: true,
    },
    {
      title: "GSTIN",
      dataIndex: "gstin",
      key: "gstin",
      render: (text: string) => text ? <code style={{ fontWeight: 600 }}>{text}</code> : <span style={{ color: "#bfbfbf" }}>N/A</span>,
    },
    {
      title: "Grand Total",
      dataIndex: "grandTotal",
      key: "grandTotal",
      align: "right" as const,
      render: (val: number) => (
        <span style={{ fontWeight: 600 }}>
          ₹{formatINR(val, 0)}
        </span>
      ),
    },
    {
      title: "Generated By",
      dataIndex: "generatedBy",
      key: "generatedBy",
      render: (text: string) => <Tag color="purple">{text}</Tag>
    }
  ];

  const savedColumns = [
    {
      title: "PI Number",
      dataIndex: "piNumber",
      key: "piNumber",
      render: (text: string) => <Tag color="green" style={{ fontSize: "0.9rem", padding: "4px 8px" }}>{text}</Tag>,
    },
    {
      title: "Date",
      dataIndex: "date",
      key: "date",
      render: (dateStr: string) => new Date(dateStr).toLocaleDateString("en-IN", {
        year: "numeric",
        month: "short",
        day: "numeric"
      })
    },
    {
      title: "Customer",
      dataIndex: "customerName",
      key: "customerName",
      ellipsis: true,
    },
    {
      title: "Grand Total",
      dataIndex: "grandTotal",
      key: "grandTotal",
      align: "right" as const,
      render: (val: number) => (
        <span style={{ fontWeight: 600 }}>
          ₹{formatINR(val, 0)}
        </span>
      ),
    },
    {
      title: "Saved At",
      dataIndex: "savedAt",
      key: "savedAt",
      render: (dateStr: string) => new Date(dateStr).toLocaleString("en-IN", {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit"
      })
    },
    {
      title: "Actions",
      key: "actions",
      render: (_: unknown, record: StoredPI) => (
        <div style={{ display: "flex", gap: 8 }}>
          <Button
            type="primary"
            size="small"
            icon={<DownloadOutlined />}
            onClick={() => handleDownloadSaved(record.piNumber)}
          >
            Download PDF
          </Button>
          <Button
            size="small"
            icon={<EyeOutlined />}
            onClick={() => setPreviewPI(record)}
          >
            Preview
          </Button>
        </div>
      )
    }
  ];

  return (
    <div className="fade-in-entry">
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
        <div>
          <h2 style={{ fontFamily: "var(--font-brand)", fontSize: "1.8rem", fontWeight: 700, margin: 0 }}>
            Dashboard Overview
          </h2>
          <p style={{ color: "var(--text-secondary-light)", margin: 0 }}>
            Welcome to the Aqueouss Proforma Invoice Management Portal.
          </p>
        </div>
        <div style={{ display: "flex", gap: 12 }}>
          <Button icon={<ReloadOutlined />} onClick={fetchDashboard} loading={loading}>
            Refresh
          </Button>
          <Button type="primary" onClick={onNavigateToCreate} className="btn-primary-grad">
            Create New PI
          </Button>
        </div>
      </div>

      {error && (
        <Alert
          message="Connection Error"
          description={error}
          type="error"
          showIcon
          style={{ marginBottom: 24 }}
          action={
            <Button size="small" danger onClick={fetchDashboard}>
              Retry Connection
            </Button>
          }
        />
      )}

      {loading && !stats ? (
        <div style={{ textAlign: "center", padding: "100px 0" }}>
          <Spin size="large" tip="Loading dashboard data..." />
        </div>
      ) : (
        <>
          <Row gutter={[20, 20]} style={{ marginBottom: 28 }}>
            <Col xs={24} sm={12} lg={8}>
              <Card bordered={false} className="glass-card" hoverable>
                <Statistic
                  title="Total PIs Generated Today"
                  value={stats?.todayCount || 0}
                  prefix={<FileTextOutlined style={{ color: "var(--primary-color)" }} />}
                  valueStyle={{ fontWeight: 700 }}
                />
              </Card>
            </Col>

            <Col xs={24} sm={12} lg={8}>
              <Card bordered={false} className="glass-card" hoverable>
                <Statistic
                  title="Total PIs This Month"
                  value={stats?.monthCount || 0}
                  prefix={<CalendarOutlined style={{ color: "#10b981" }} />}
                  valueStyle={{ fontWeight: 700 }}
                />
              </Card>
            </Col>

            <Col xs={24} sm={24} lg={8}>
              <Card bordered={false} className="glass-card" hoverable>
                <Statistic
                  title="Last Generated PI Number"
                  value={stats?.lastPiNumber || "N/A"}
                  prefix={<NumberOutlined style={{ color: "#f59e0b" }} />}
                  valueStyle={{ fontSize: "1.3rem", fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis" }}
                />
              </Card>
            </Col>
          </Row>

          <Card
            title={
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <SaveOutlined style={{ color: "#10b981" }} />
                <span style={{ fontFamily: "var(--font-brand)", fontWeight: 600 }}>Saved Invoices (This Device)</span>
              </div>
            }
            bordered={false}
            className="glass-card"
            style={{ marginBottom: 28 }}
          >
            {savedPIs.length === 0 ? (
              <Empty description="No saved PIs on this device yet. Generate a PI to see it here." />
            ) : (
              <Table
                dataSource={savedPIs}
                columns={savedColumns}
                rowKey="piNumber"
                pagination={false}
                scroll={{ x: true }}
              />
            )}
          </Card>

          <Card
            title={
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <DollarCircleOutlined style={{ color: "var(--primary-color)" }} />
                <span style={{ fontFamily: "var(--font-brand)", fontWeight: 600 }}>Recent Proforma Invoices</span>
              </div>
            }
            bordered={false}
            className="glass-card"
          >
            <Table
              dataSource={recentPIs}
              columns={columns}
              rowKey="piNumber"
              loading={loading}
              pagination={{ pageSize: 5 }}
              scroll={{ x: true }}
            />
          </Card>
        </>
      )}

      <Modal
        open={!!previewPI}
        onCancel={() => setPreviewPI(null)}
        destroyOnClose
        footer={null}
        width={900}
        style={{ top: 20 }}
      >
        {previewPI && (
          <PIPreview
            data={previewPI.invoiceData}
            onClose={() => setPreviewPI(null)}
            readOnly
          />
        )}
      </Modal>
    </div>
  );
};
