import React, { useEffect, useState } from "react";
import { Card, Col, Row, Statistic, Table, Tag, Button, Spin, Alert } from "antd";
import { 
  FileTextOutlined, 
  CalendarOutlined, 
  NumberOutlined, 
  ReloadOutlined,
  DollarCircleOutlined
} from "@ant-design/icons";
import { getDashboardData } from "../api";
import { PILogEntry, DashboardStats, User } from "../types";

interface DashboardProps {
  currentUser: User;
  onNavigateToCreate: () => void;
}

export const Dashboard: React.FC<DashboardProps> = ({ onNavigateToCreate }) => {
  const [loading, setLoading] = useState(true);
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [recentPIs, setRecentPIs] = useState<PILogEntry[]>([]);
  const [error, setError] = useState<string | null>(null);

  const fetchDashboard = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await getDashboardData();
      setStats(result.stats);
      setRecentPIs(result.recentPIs);
    } catch (err: any) {
      setError(err.message || "Failed to load dashboard data");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDashboard();
  }, []);

  const columns = [
    {
      title: "PI Number",
      dataIndex: "piNumber",
      key: "piNumber",
      render: (text: string) => <Tag color="blue" style={{ fontSize: "0.9rem", padding: "4px 8px" }}>{text}</Tag>,
    },
    {
      title: "Date",
      dataIndex: "date",
      key: "date",
      render: (dateStr: string) => new Date(dateStr).toLocaleDateString("en-IN", {
        year: 'numeric',
        month: 'short',
        day: 'numeric'
      })
    },
    {
      title: "Customer Name",
      dataIndex: "customerName",
      key: "customerName",
      ellipsis: true,
    },
    {
      title: "GSTIN",
      dataIndex: "gstin",
      key: "gstin",
      render: (text: string) => text ? <code style={{ fontWeight: 600 }}>{text}</code> : <span style={{ color: "#bfbfbf" }}>N/A</span>,
    },
    {
      title: "Grand Total",
      dataIndex: "grandTotal",
      key: "grandTotal",
      align: "right" as const,
      render: (val: number) => (
        <span style={{ fontWeight: 600 }}>
          ₹{val.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
        </span>
      ),
    },
    {
      title: "Generated By",
      dataIndex: "generatedBy",
      key: "generatedBy",
      render: (text: string) => <Tag color="purple">{text}</Tag>
    }
  ];

  return (
    <div className="fade-in-entry">
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 24 }}>
        <div>
          <h2 style={{ fontFamily: "var(--font-brand)", fontSize: "1.8rem", fontWeight: 700, margin: 0 }}>
            Dashboard Overview
          </h2>
          <p style={{ color: "var(--text-secondary-light)", margin: 0 }}>
            Welcome to the Aqueouss Proforma Invoice Management Portal.
          </p>
        </div>
        <div style={{ display: "flex", gap: 12 }}>
          <Button icon={<ReloadOutlined />} onClick={fetchDashboard} loading={loading}>
            Refresh
          </Button>
          <Button type="primary" onClick={onNavigateToCreate} className="btn-primary-grad">
            Create New PI
          </Button>
        </div>
      </div>

      {error && (
        <Alert
          message="Connection Error"
          description={error}
          type="error"
          showIcon
          style={{ marginBottom: 24 }}
          action={
            <Button size="small" danger onClick={fetchDashboard}>
              Retry Connection
            </Button>
          }
        />
      )}

      {loading && !stats ? (
        <div style={{ textAlign: "center", padding: "100px 0" }}>
          <Spin size="large" tip="Loading dashboard data..." />
        </div>
      ) : (
        <>
          <Row gutter={[20, 20]} style={{ marginBottom: 28 }}>
            <Col xs={24} sm={12} lg={8}>
              <Card bordered={false} className="glass-card" hoverable>
                <Statistic
                  title="Total PIs Generated Today"
                  value={stats?.todayCount || 0}
                  prefix={<FileTextOutlined style={{ color: "var(--primary-color)" }} />}
                  valueStyle={{ fontWeight: 700 }}
                />
              </Card>
            </Col>
            
            <Col xs={24} sm={12} lg={8}>
              <Card bordered={false} className="glass-card" hoverable>
                <Statistic
                  title="Total PIs This Month"
                  value={stats?.monthCount || 0}
                  prefix={<CalendarOutlined style={{ color: "#10b981" }} />}
                  valueStyle={{ fontWeight: 700 }}
                />
              </Card>
            </Col>

            <Col xs={24} sm={24} lg={8}>
              <Card bordered={false} className="glass-card" hoverable>
                <Statistic
                  title="Last Generated PI Number"
                  value={stats?.lastPiNumber || "N/A"}
                  prefix={<NumberOutlined style={{ color: "#f59e0b" }} />}
                  valueStyle={{ fontSize: "1.3rem", fontWeight: 700, overflow: "hidden", textOverflow: "ellipsis" }}
                />
              </Card>
            </Col>
          </Row>

          <Card 
            title={
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <DollarCircleOutlined style={{ color: "var(--primary-color)" }} />
                <span style={{ fontFamily: "var(--font-brand)", fontWeight: 600 }}>Recent Proforma Invoices</span>
              </div>
            }
            bordered={false} 
            className="glass-card"
          >
            <Table
              dataSource={recentPIs}
              columns={columns}
              rowKey="piNumber"
              loading={loading}
              pagination={{ pageSize: 5 }}
              scroll={{ x: true }}
            />
          </Card>
        </>
      )}
    </div>
  );
};
